import { scanHTML } from './scanner.js';
import { applyFixes } from './fixer.js';

/**
 * A11y Fix Engine — scan HTML for WCAG violations and auto-fix what we can.
 *
 * @param {string} html - HTML content to scan and fix
 * @param {object} options
 * @param {string} options.standard - WCAG level: 'wcag2a' | 'wcag2aa' | 'wcag2aaa'
 * @param {boolean} options.fixEnabled - Whether to apply auto-fixes (default: true)
 * @returns {Promise<EngineResult>}
 */
export async function runEngine(html, options = {}) {
  const { standard = 'wcag2aa', fixEnabled = true } = options;

  // Step 1: Scan for violations
  const scanResult = await scanHTML(html, { standard });

  // Step 2: Apply fixes if enabled
  let fixResult = { fixedHTML: html, fixes: [], unfixable: [] };
  if (fixEnabled && scanResult.violations.length > 0) {
    fixResult = applyFixes(html, scanResult.violations);
  }

  // Step 3: Generate report
  const report = generateReport(scanResult, fixResult);

  return {
    originalHTML: html,
    fixedHTML: fixResult.fixedHTML,
    report,
    scan: scanResult.summary,
    fixes: fixResult.fixes,
    unfixable: fixResult.unfixable,
  };
}

/**
 * Generate a human-readable Markdown report.
 */
function generateReport(scanResult, fixResult) {
  const { fixes, unfixable } = fixResult;
  const { summary } = scanResult;

  const lines = [];
  lines.push('# Accessibility Fix Report');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total violations found | ${summary.totalViolations} |`);
  lines.push(`| Total affected elements | ${summary.totalIssues} |`);
  lines.push(`| Critical | ${summary.critical} |`);
  lines.push(`| Serious | ${summary.serious} |`);
  lines.push(`| Moderate | ${summary.moderate} |`);
  lines.push(`| Minor | ${summary.minor} |`);
  lines.push(`| **Auto-fixed** | **${fixes.length}** |`);
  lines.push(`| Requires manual review | ${unfixable.length} |`);
  lines.push('');

  if (fixes.length > 0) {
    lines.push('## Auto-Fixed Issues');
    lines.push('');
    for (const fix of fixes) {
      lines.push(`### ${fix.description}`);
      lines.push(`- **WCAG:** ${fix.wcag} | **Impact:** ${fix.impact} | **Fix:** ${fix.fixType}`);
      lines.push(`- **Note:** ${fix.note}`);
      lines.push('');
      lines.push('<details><summary>View code change</summary>');
      lines.push('');
      lines.push('**Before:**');
      lines.push('```html');
      lines.push(fix.before);
      lines.push('```');
      lines.push('');
      lines.push('**After:**');
      lines.push('```html');
      lines.push(fix.after);
      lines.push('```');
      lines.push('</details>');
      lines.push('');
    }
  }

  if (unfixable.length > 0) {
    lines.push('## Requires Manual Review');
    lines.push('');
    lines.push('The following issues were detected but require human judgment to fix:');
    lines.push('');
    for (const issue of unfixable) {
      lines.push(`- **${issue.description}** (WCAG ${issue.wcag}, ${issue.impact}) — ${issue.nodes} element(s)`);
      if (issue.reason) lines.push(`  - Reason: ${issue.reason}`);
      if (issue.helpUrl) lines.push(`  - [Learn more](${issue.helpUrl})`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [a11y-fix-engine](https://github.com/a11y-fix-engine) — AI-powered WCAG auto-remediation*');

  return lines.join('\n');
}

export { scanHTML } from './scanner.js';
export { applyFixes } from './fixer.js';
